---
- name: Copy from docker
  shell: "docker cp -L {{container_name}}:{{dotOne_path_docker}} {{dotOne_path}}"
- name: Create directory
  file:
    path: files/dotOne
    state: directory
- name: Copy from remote to localhost
  fetch:
    src: "{{item}}"
    dest: "{{dotOne_path_local}}"
    flat: true
    recurse: true
  loop:
    - "{{ dotOne_path }}/one_auth"
    - "{{ dotOne_path }}/oneflow_auth"
    - "{{ dotOne_path }}/onegate_auth"
    - "{{ dotOne_path }}/sunstone_auth"
