---
- name: Create directory
  file:
    path: files/dotOne
    state: directory
- name: Copy file to remote host
  copy:
    src: "{{item}}"
    dest: "{{ dotOne_path }}"
  loop:
    - "{{ dotOne_path_local }}/one_auth"
    - "{{ dotOne_path_local }}/oneflow_auth"
    - "{{ dotOne_path_local }}/onegate_auth"
    - "{{ dotOne_path_local }}/sunstone_auth"
- name: Copy file to {{ container_name }} container
  shell: docker cp {{ dotOne_path }} {{ container_name }}:{{dotOne_path_docker}} 
- name: Change .one owner to oneadmin
  shell: docker exec {{ container_name }} chown oneadmin:oneadmin {{ dotOne_path_docker }} 
