---
- name: Start all containers
  hosts: all
  gather_facts: no
  vars_files:
    - defaults/main.yaml
  tasks:
    - name: Create ansible directory for docker
      file:
        path: /var/tmp/ansible
        state: directory
        owner: oneadmin
        group: oneadmin
    - name: Add docker to autostart
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
    - name: Start Container 
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        network_mode: host
        stop_timeout: 90
        security_opts: "seccomp:unconfined"
        restart_policy: "always"
        volumes:
          - hvol:/hvol
          - /var/tmp:/var/tmp
        pull: false
        state: started
  tags: docker_init
- name: Setup master zone
  hosts: master
  gather_facts: no
  vars_files:
    - defaults/main.yaml
  tasks:
    - block:
      - name: Configure /etc/one/oned.conf
        include_role: 
          name: oned_configure
      - name: Restart oned
        include_role:
          name: oned_restart
      tags: configure_oned
    - block:
      - name: Update zones endpoints
        include_role:
          name: endpoint_update
        vars:
          zone_name: "{{ hostvars[item]['zone'] | default(item) }}"
          endpoint_ip: "{{ hostvars[item]['endpoint'] | default(hostvars[item]['ansible_host']) }}"
          host_name: "{{ item }}"
        loop: "{{ groups['slaves'] }} + {{ groups['master'] }}"
      tags: update_zones
    - block:
      - name: Backup federation table to host
        include_role:
          name: federationDB_backup
      - name: Fetch .one from remote to localhost
        include_role:
          name: dotOneToHost
      - name: Fetch table from remote to localhost
        fetch:
          src: "{{ fedDB_path }}"
          dest: "{{ fedDB_path_local }}"
          flat: true
      tags: federation_fetch
    - name: Set zone_id for all hosts
      include: tasks/setZonesID.yaml
      vars:
        zone_name: "{{ hostvars[item]['zone'] | default(item) }}"
        host_name: "{{ item }}"
      loop: "{{ groups['slaves'] }} + {{ groups['master'] }}"
- name: Setup slave zones
  hosts: slaves
  gather_facts: no
  vars_files:
    - defaults/main.yaml
  tasks:
    - name: Configure /etc/one/oned.conf
      include_role:
        name: oned_configure
    - name: Restore from federation table backup
      include_role:
        name: federationDB_restore
    - name: Copy .one from localhost to container
      include_role:
        name: dotOneToSlaves
    - name: Restart oned
      include_role:
        name: oned_restart
