---
- name: Copy file 
  copy:
    src: {{ dotOne_path_local }}
    dest: {{ dotOne_path }}
- name: Copy file to docker 
  shell: docker cp {{ dotOne_path }} {{ container_name }}:{{dotOne_path_docker}} 
