# ---------------------------------------------------------------------------- #
# Copyright 2020-2021, OpenNebula Project, OpenNebula Systems                  #
#                                                                              #
# Licensed under the Apache License, Version 2.0 (the "License"); you may      #
# not use this file except in compliance with the License. You may obtain      #
# a copy of the License at                                                     #
#                                                                              #
# http://www.apache.org/licenses/LICENSE-2.0                                   #
#                                                                              #
# Unless required by applicable law or agreed to in writing, software          #
# distributed under the License is distributed on an "AS IS" BASIS,            #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.     #
# See the License for the specific language governing permissions and          #
# limitations under the License.                                               #
# ---------------------------------------------------------------------------- #

# This is the referential docker-compose deployment for the official
# OpenNebula front-end container image.

###############################################################################
# PLEASE DO NOT EDIT THIS FILE !                                              #
###############################################################################

version: '3.7'

# common default settings
x-service:
  &default-service
  image: "${DEPLOY_OPENNEBULA_IMAGE_NAME:-docker.io/opennebula/opennebula}:${DEPLOY_OPENNEBULA_IMAGE_TAG:-6.0.0}"
  init: true
  env_file:
    - "default.env"
    - ".env"
  healthcheck:
    test: ["CMD", "/frontend-healthcheck.sh"]
    interval: "10s"
    timeout: "10s"
    retries: 3
    start_period: "2m"
  tmpfs:
    - /tmp:exec
    - /run
    - /run/lock
  networks:
    - onenet
  restart: "${DEPLOY_RESTART_POLICY:-unless-stopped}"
  stop_grace_period: "90s"

volumes:
  opennebula_backups_db:
  opennebula_fireedge:
  opennebula_datastores:
  opennebula_etcd:
  opennebula_etcd_secrets:
  opennebula_logs:
  opennebula_mysql:
  opennebula_oneadmin_auth:
  opennebula_oneadmin_ssh:
  opennebula_shared_tmp:
  opennebula_shared_vmrc:

networks:
  onenet:
#    external: true

services:
  opennebula-etcd:
    << : *default-service
    environment:
      OPENNEBULA_SERVICE: "etcd"
    volumes:
      - ./config:/config:ro,z
      - opennebula_etcd:/srv/one/etcd
      - opennebula_etcd_secrets:/srv/one/etcd-secrets
      - ./certs:/certs:z
      - ./ssh:/ssh:z

  opennebula-mysql:
    << : *default-service
    environment:
      OPENNEBULA_SERVICE: "mysqld"
    volumes:
      - ./config:/config:ro,z
      - opennebula_etcd_secrets:/srv/one/etcd-secrets
      - opennebula_mysql:/var/lib/mysql

  opennebula-docker:
    << : *default-service
    privileged: true
    environment:
      OPENNEBULA_SERVICE: "docker"
    volumes:
      - ./config:/config:ro,z

  opennebula-oned:
    << : *default-service
    #privileged: true
    cap_add:
      - SYS_ADMIN
    # the default apparmor profile - docker-default - is preventing the fuse2fs
    # from mounting disks and therefore renders Docker Hub marketplace unusable
    security_opt:
      - "apparmor=${DEPLOY_APPARMOR_PROFILE:-unconfined}"
    environment:
      OPENNEBULA_SERVICE: "oned"
      MONITORD_PORT: "${DEPLOY_MONITORD_EXTERNAL_PORT:-4124}"
      ONEGATE_PORT: "${DEPLOY_ONEGATE_EXTERNAL_PORT:-5030}"
    depends_on:
      - opennebula-mysql
    ports:
      - "${DEPLOY_BIND_ADDR:-0.0.0.0}:${DEPLOY_ONED_EXTERNAL_PORT:-2633}:${DEPLOY_ONED_INTERNAL_PORT:-2634}"  # TLS
      - "${DEPLOY_BIND_ADDR:-0.0.0.0}:${DEPLOY_MONITORD_EXTERNAL_PORT:-4124}:${DEPLOY_MONITORD_EXTERNAL_PORT:-4124}"
      - "${DEPLOY_BIND_ADDR:-0.0.0.0}:${DEPLOY_MONITORD_EXTERNAL_PORT:-4124}:${DEPLOY_MONITORD_EXTERNAL_PORT:-4124}/udp"
    volumes:
      - ./config:/config:ro,z
      - opennebula_backups_db:/var/lib/one/backups/db
      - "${DEPLOY_VOLUME_DATASTORES:-opennebula_datastores}:/var/lib/one/datastores:z"
      - opennebula_etcd_secrets:/srv/one/etcd-secrets
      - opennebula_oneadmin_auth:/var/lib/one/.one
      - opennebula_logs:/var/log/one
      - opennebula_shared_tmp:/var/tmp/sunstone
    devices:
      - /dev/fuse:/dev/fuse

  opennebula-sshd:
    << : *default-service
    cap_add:
      - AUDIT_WRITE
    environment:
      OPENNEBULA_SERVICE: "sshd"
    ports:
      - "${DEPLOY_BIND_SSH_ADDR:-0.0.0.0}:${DEPLOY_SSH_EXTERNAL_PORT:-22}:22"
    depends_on:
      - opennebula-oned
    volumes:
      - ./config:/config:ro,z
      - "${DEPLOY_VOLUME_DATASTORES:-opennebula_datastores}:/var/lib/one/datastores:z"
      - opennebula_etcd_secrets:/srv/one/etcd-secrets
      - opennebula_oneadmin_ssh:/var/lib/one/.ssh

  opennebula-memcached:
    << : *default-service
    environment:
      OPENNEBULA_SERVICE: "memcached"
    volumes:
      - ./config:/config:ro,z

  opennebula-scheduler:
    << : *default-service
    environment:
      OPENNEBULA_SERVICE: "scheduler"
    depends_on:
      - opennebula-oned
    volumes:
      - ./config:/config:ro,z
      - opennebula_oneadmin_auth:/var/lib/one/.one:ro
      - opennebula_logs:/var/log/one

  opennebula-flow:
    << : *default-service
    environment:
      OPENNEBULA_SERVICE: "oneflow"
    depends_on:
      - opennebula-oned
    ports:
      - "${DEPLOY_BIND_ADDR:-0.0.0.0}:${DEPLOY_ONEFLOW_EXTERNAL_PORT:-2474}:${DEPLOY_ONEFLOW_INTERNAL_PORT:-2475}"  # TLS
    volumes:
      - ./config:/config:ro,z
      - opennebula_etcd_secrets:/srv/one/etcd-secrets
      - opennebula_oneadmin_auth:/var/lib/one/.one:ro
      - opennebula_logs:/var/log/one

  opennebula-gate:
    << : *default-service
    environment:
      OPENNEBULA_SERVICE: "onegate"
    depends_on:
      - opennebula-oned
    ports:
      - "${DEPLOY_BIND_ONEGATE_ADDR:-0.0.0.0}:${DEPLOY_ONEGATE_EXTERNAL_PORT:-5030}:${DEPLOY_ONEGATE_INTERNAL_PORT:-5031}"  # TLS
    volumes:
      - ./config:/config:ro,z
      - opennebula_etcd_secrets:/srv/one/etcd-secrets
      - opennebula_oneadmin_auth:/var/lib/one/.one:ro
      - opennebula_logs:/var/log/one

  opennebula-guacd:
    << : *default-service
    environment:
      OPENNEBULA_SERVICE: "guacd"
    volumes:
      - ./config:/config:ro,z

  opennebula-sunstone:
    << : *default-service
    environment:
      OPENNEBULA_SERVICE: "sunstone"
      SUNSTONE_PORT: "${DEPLOY_SUNSTONE_EXTERNAL_PORT:-80}"
      SUNSTONE_TLS_PORT: "${DEPLOY_SUNSTONE_EXTERNAL_TLS_PORT:-443}"
      SUNSTONE_VNC_PORT: "${DEPLOY_SUNSTONE_EXTERNAL_VNC_PORT:-29876}"
    depends_on:
      - opennebula-oned
    ports:
      - "${DEPLOY_BIND_ADDR:-0.0.0.0}:${DEPLOY_SUNSTONE_EXTERNAL_PORT:-80}:80"
      - "${DEPLOY_BIND_ADDR:-0.0.0.0}:${DEPLOY_SUNSTONE_EXTERNAL_TLS_PORT:-443}:443"
      - "${DEPLOY_BIND_ADDR:-0.0.0.0}:${DEPLOY_SUNSTONE_EXTERNAL_VNC_PORT:-29876}:${DEPLOY_SUNSTONE_EXTERNAL_VNC_PORT:-29876}"
    volumes:
      - ./config:/config:ro,z
      - opennebula_etcd_secrets:/srv/one/etcd-secrets
      - opennebula_oneadmin_auth:/var/lib/one/.one:ro
      - opennebula_logs:/var/log/one
      - opennebula_shared_tmp:/var/tmp/sunstone
      - opennebula_shared_vmrc:/var/lib/one/sunstone_vmrc_tokens

  opennebula-fireedge:
    << : *default-service
    environment:
      OPENNEBULA_SERVICE: "fireedge"
    depends_on:
      - opennebula-oned
    volumes:
      - ./config:/config:ro,z
      - opennebula_etcd_secrets:/srv/one/etcd-secrets
      - opennebula_fireedge:/var/lib/one/fireedge
      - opennebula_oneadmin_auth:/var/lib/one/.one
      - opennebula_logs:/var/log/one
      - opennebula_shared_vmrc:/var/lib/one/sunstone_vmrc_tokens

  opennebula-provision:
    << : *default-service
    cap_add:
      - AUDIT_WRITE
    environment:
      OPENNEBULA_SERVICE: "oneprovision"
    volumes:
      - ./config:/config:ro,z
      - opennebula_etcd_secrets:/srv/one/etcd-secrets
      - opennebula_fireedge:/var/lib/one/fireedge
      - opennebula_oneadmin_auth:/var/lib/one/.one
      - opennebula_logs:/var/log/one
