---
- name: ensure systemd service override directory exists
  file:
    state: directory
    path: "/etc/systemd/system/ceph-mgr@.service.d/"
  when:
    - ceph_mgr_systemd_overrides is defined
    - ansible_service_mgr == 'systemd'

- name: add ceph-mgr systemd service overrides
  config_template:
    src: "ceph-mgr.service.d-overrides.j2"
    dest: "/etc/systemd/system/ceph-mgr@.service.d/ceph-mgr-systemd-overrides.conf"
    config_overrides: "{{ ceph_mgr_systemd_overrides | default({}) }}"
    config_type: "ini"
  when:
    - ceph_mgr_systemd_overrides is defined
    - ansible_service_mgr == 'systemd'

- name: include_tasks systemd.yml
  include_tasks: systemd.yml
  when: containerized_deployment | bool

- name: systemd start mgr
  systemd:
    name: ceph-mgr@{{ ansible_hostname }}
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes
  when: ansible_service_mgr == 'systemd'

- name: ensure OpenRC link for service
  file:
      path: /etc/init.d/ceph-mgr.{{ ansible_hostname }}
      src: ceph
      state: link
  when: ansible_service_mgr == 'openrc'

- name: OpenRC start mgr
  service:
    name: "ceph-mgr.{{ ansible_hostname }}"
    state: started
    enabled: yes
  when: ansible_service_mgr == 'openrc'
