---
- name: Setup backup system
  hosts: backuper
  gather_facts: no
  vars_files:
    - defaults/main.yaml
  tasks:
    - name: Check if bus image exists
      docker_image:
        name: "{{ docker_bus_image }}"
      register: image_exists

    - name: Load all image(s) from the given tar file
      community.docker.docker_image_load:
        path: files/{{ docker_bus_path }}
      register: result
      when: not image_exists | length == 1

    - name: Print the loaded image names
      ansible.builtin.debug:
        msg: "Loaded the following images: {{ result.image_names | join(', ') }}"
      when: not image_exists | length == 1
    
    - name: Sign images
      shell: hvs_sign  
      when: not image_exists | length == 1

    - name: Make directory
      file:
        path: /home/backuplogs

    - name: Create backup.conf
      copy:
        src: files/backup.conf
        dest: /home/backuplogs/backup.conf
    
    - name: Create backuper user
      hosts: oned
      community.docker.docker_container_exec:
        container: "{{ docker_one_name }}"
        command: "{{ oneuser }} create backuper backuper"

    - name: Run container
      docker_container:
        name: "{{ docker_bus_name }}"
        image: "{{ docker_bus_image }}" 
        pull: false
        net: host
        volumes:
          - /home/backuplogs:/var/log/one/backup
        command: "/bin/bash /opt/backup/start"
        state: started

    - name: chmod id_rsa
      community.docker.docker_container_exec:
        container: "{{ docker_bus_name }}"
        command: "chmod 0600 /root/.ssh/id_rsa"
