---
- name: Backup federation
  shell: "docker exec {{container_name}} onedb backup -f --federated -u{{ onedb_user }} -p{{ onedb_pass }} -d opennebula {{fedDB_path_docker}}"
- name: Copy backup to host
  shell: "docker cp {{container_name}}:{{fedDB_path_docker}} {{fedDB_path}}"
