#zone: name that will be given to zone(host name by default)
#endpoint: endpoint ip that will be assign to zone (ansible_host by default)
all:
  hosts:
    h23:
      user: root
      zone: Horizon
      endpoint: "10.10.101.23"
    h25:
      user: root
      ansible_host: 10.10.101.25
  children:
    master:
      hosts:
        h23
      vars:
        federation_mode: "MASTER"
        zone_id: 0
    slaves:
      hosts:
        h25
      vars:
        federation_mode: "SLAVE"
