---
- name: Copy federation table backup from localhost
  copy:
    src: "{{ fedDB_path_local }}"
    dest: "{{ fedDB_path }}"
- name: Copy backup to docker
  shell: "docker cp {{fedDB_path}} {{container_name}}:{{fedDB_path_docker}}"
- name: Stop Opennebula
  shell: "docker exec {{container_name}} one stop"
- name: Restore federaion from backup
  shell: "docker exec {{ container_name }} onedb restore --federated -u{{ onedb_user }} -p{{ onedb_pass }} -d opennebula {{fedDB_path_docker}}"
