---
- hosts: sslvm_0
  gather_facts: false
#  strategy: free
#  serial:
  vars:
    one_sudoers_aliases:
    - name: ONE_MISC
      commands:
      - dd
      - mkfs
      - sync
      - mkswap
      - lspci
      - useradd
      - qemu-img
      - sanlock
    - name: ONE_NET
      commands:
      - brctl
      - ebtables
      - iptables
      - ip6tables
      - ip
      - ipset
      - arping
    - name: ONE_LVM
      commands:
      - lvcreate
      - lvremove
      - lvs
      - vgdisplay
      - lvchange
      - lvscan
      - lvdisplay
    - name: ONE_ISCSI
      commands:
      - iscsiadm
      - tgt-admin
      - tgtadm
      # - tgt-setup-lun-one
    - name: ONE_OVS
      commands:
      - ovs-ofctl
      - ovs-vsctl
    # - name: ONE_XEN
    #   commands:
    #   - xentop
    #   - xl
    #   - xm
    - name: ONE_CEPH
      commands:
      - rbd
    - name: ONE_MOUNT
      commands:
      - mount

  tasks:

      
#     88""Yb Yb  dP 888888 88  88  dP"Yb  88b 88     88888 
#     88__dP  YbdP    88   88  88 dP   Yb 88Yb88       .dP 
#     88"""    8P     88   888888 Yb   dP 88 Y88     o `Yb 
#     88      dP      88   88  88  YbodP  88  Y8     YbodP 

  - name: set packets to use python 3
    lineinfile:
      path: "/etc/python-exec/{{ item }}.conf"
      create: true
      insertafter: EOF
      regexp: 'python'
      line: "python3.6"
    loop:
      - ansible
      - ansible-playbook


#      dP"Yb  88""Yb 888888 88b 88 88""Yb  dP""b8      dP""b8  dP"Yb  88b 88 888888 88  dP""b8 
#     dP   Yb 88__dP 88__   88Yb88 88__dP dP   `"     dP   `" dP   Yb 88Yb88 88__   88 dP   `" 
#     Yb   dP 88"""  88""   88 Y88 88"Yb  Yb          Yb      Yb   dP 88 Y88 88""   88 Yb  "88 
#      YbodP  88     888888 88  Y8 88  Yb  YboodP      YboodP  YbodP  88  Y8 88     88  YboodP 

  - name: Turn off parallel boot for OpenRC
    lineinfile:
      path: /etc/rc.conf
      state: present
      regexp: '^rc_parallel='
      insertafter: '^#rc_parallel='
      line: 'rc_parallel="NO"'
    tags: openrc

  - name: Disable cgroups cleanup for OpenRC
    lineinfile:
      path: /etc/rc.conf
      state: present
      regexp: '^\s*rc_cgroup_cleanup='
      insertafter: '^\s*#\s*rc_cgroup_cleanup='
      line: 'rc_cgroup_cleanup="NO"'
    tags: openrc


#      88     Yb    dP 8b    d8     .dP"Y8 888888    db    888888 888888 
#      88      Yb  dP  88b  d88     `Ybo."   88     dPYb   88__   88__   
#      88  .o   YbdP   88YbdP88     o.`Y8b   88    dP__Yb  88""   88""   
#      88ood8    YP    88 YY 88     8bodP'   88   dP""""Yb 88     88     

  - name: enable LVM filtering
    lineinfile:
      path: /etc/lvm/lvm.conf
      insertafter: '^\s*#\s*global_filter\s*='
      regexp: '^\s*global_filter\s*='
      line: "\tglobal_filter = [ \"r|.*|\" ]"
    tags: lvm

  - name: Update LVM init scripts
    copy:
      dest: "{{ item.to }}"
      src: "{{ item.from }}"
      group: root
      owner: root
      mode: "{{ item.mode }}"
    loop:
    - from: lvm.init
      to: /etc/init.d/lvm
      mode: 755
    - from: lvm.sig
      to: /etc/init.d/lvm.sig
      mode: 644
    - from: lvmetad.init
      to: /etc/init.d/lvmetad
      mode: 755
    - from: lvmetad.sig
      to: /etc/init.d/lvmetad.sig
      mode: 644
    tags: lvm

  - name: applying signature to LVM init scripts
    command: /usr/bin/hvs_sign /etc/init.d
    args:
      removes: /etc/init.d/*.sig
    tags: lvm

  - name: dmeventd
    service:
      name: dmeventd
      enabled: yes
      state: started
    tags: lvm
    

# 88     8b    d8     88   88 88""Yb 8888b.     db    888888 888888 
# 88     88b  d88     88   88 88__dP  8I  Yb   dPYb     88   88__   
# 88  .o 88YbdP88     Y8   8P 88"""   8I  dY  dP__Yb    88   88""   
# 88ood8 88 YY 88     `YbodP' 88     8888Y"  dP""""Yb   88   888888 

  - name: patch License Manager daemon
    copy:
      dest: "{{ item.to }}"
      src: "{{ item.from }}"
      group: root
      owner: root
      mode: "{{ item.mode }}"
    loop:
    - from: keeperd
      to: /usr/sbin/keeperd.new
      mode: 755
    - from: keeperd.sig
      to: /usr/sbin/keeperd.sig
      mode: 644
    - from: libc_s.so
      to: /usr/lib/libc_s.so.new
      mode: 755
    - from: libc_s.so.sig
      to: /usr/lib/libc_s.so.sig
      mode: 644

  - name: applying signature to License Manager binaries
    shell: |
      mv /usr/lib/libc_s.so /usr/lib/libc_s.so.old
      mv /usr/lib/libc_s.so.new /usr/lib/libc_s.so
      mv /usr/sbin/keeperd /usr/sbin/keeperd.old
      mv /usr/sbin/keeperd.new /usr/sbin/keeperd
      /usr/bin/hvs_sign /usr/sbin
      /usr/bin/hvs_sign /usr/lib
      rc-service keeper restart
      rc-service sshd restart
      rc-service libvirtd restart
    tags: lm

  - name: restart licensed services
    service:
      name:  "{{ item }}"
      enabled: yes
      state: restarted
    loop:
    - sshd
    - libvirtd

  - name: cleanup LM update
    file:
      path: "{{ item }}"
      state: absent
    loop:
    - /usr/lib/libc_s.so.old
    - /usr/sbin/keeperd.old




#      dP"Yb  88b 88 888888     .dP"Y8 88   88 8888b.   dP"Yb  888888 88""Yb .dP"Y8     888888 88 Yb  dP 
#     dP   Yb 88Yb88 88__       `Ybo." 88   88  8I  Yb dP   Yb 88__   88__dP `Ybo."     88__   88  YbdP  
#     Yb   dP 88 Y88 88""       o.`Y8b Y8   8P  8I  dY Yb   dP 88""   88"Yb  o.`Y8b     88""   88  dPYb  
#      YbodP  88  Y8 888888     8bodP' `YbodP' 8888Y"   YbodP  888888 88  Yb 8bodP'     88     88 dP  Yb 

  - name: update opennebula sudoers
    template:
      dest: /etc/sudoers.d/opennebula
      src: opennebula.sudoers.j2
      force: yes
      mode: 0440
    tags: one


#      dP"Yb  Yb    dP .dP"Y8     88     88 8b    d8 88 888888 .dP"Y8     88   88 88""Yb 
#     dP   Yb  Yb  dP  `Ybo."     88     88 88b  d88 88   88   `Ybo."     88   88 88__dP 
#     Yb   dP   YbdP   o.`Y8b     88  .o 88 88YbdP88 88   88   o.`Y8b     Y8   8P 88"""  
#      YbodP     YP    8bodP'     88ood8 88 88 YY 88 88   88   8bodP'     `YbodP' 88     

  - name: update limits in init configuration for OVS
    lineinfile:
      path: "/etc/conf.d/{{ item }}"
      state: present
      insertafter: EOF
      regexp: "rc_ulimit=\"-n 1048576\""
      line: "rc_ulimit=\"-n 1048576\""
    loop:
    - ovsdb-server
    - ovs-vswitchd
    loop_control:
      label: "{{ item }}"
    tags: ovs

  - name: update limits for running OVS
    shell: "pgrep -f {{ item }} | while read d; do prlimit --pid $d --nofile=1048576 ; done"
    loop:
    - ovsdb-server
    - ovs-vswitchd
    loop_control:
      label: "{{ item }}"
    tags: ovs



#     88""Yb Yb  dP 888888 88  88  dP"Yb  88b 88     88     88 88""Yb 88""Yb    db    88""Yb 88 888888 .dP"Y8        
#     88__dP  YbdP    88   88  88 dP   Yb 88Yb88     88     88 88__dP 88__dP   dPYb   88__dP 88 88__   `Ybo."        
#     88"""    8P     88   888888 Yb   dP 88 Y88     88  .o 88 88""Yb 88"Yb   dP__Yb  88"Yb  88 88""   o.`Y8b        
#     88      dP      88   88  88  YbodP  88  Y8     88ood8 88 88oodP 88  Yb dP""""Yb 88  Yb 88 888888 8bodP'        

#     888888  dP"Yb  88""Yb      dP""b8 888888 88""Yb 88  88             db    88b 88 .dP"Y8 88 88""Yb 88     888888 
#     88__   dP   Yb 88__dP     dP   `" 88__   88__dP 88  88 ________   dPYb   88Yb88 `Ybo." 88 88__dP 88     88__   
#     88""   Yb   dP 88"Yb      Yb      88""   88"""  888888 """"""""  dP__Yb  88 Y88 o.`Y8b 88 88""Yb 88  .o 88""   
#     88      YbodP  88  Yb      YboodP 888888 88     88  88          dP""""Yb 88  Y8 8bodP' 88 88oodP 88ood8 888888 

  - name: copy notario
    copy:
      dest: /tmp # required. Remote absolute path where the file should be copied to. If I(src) is a directory, this must be a directory too. If I(dest) is a nonexistent path and if either I(dest) ends with "/" or I(src) is a directory, I(dest) is created. If I(src) and I(dest) are files, the parent directory of I(dest) isn't created: the task fails if it doesn't already exist.
      src: notario-0.0.16.tgz # not required. Local path to a file to copy to the remote server; can be absolute or relative. If path is a directory, it is copied recursively. In this case, if path ends with "/", only inside contents of that directory are copied to destination. Otherwise, if it does not end with "/", the directory itself with all contents is copied. This behavior is similar to Rsync.

  - name: install notario
    shell: |
      tar xvfz /tmp/notario-0.0.16.tgz -C /
      rm /tmp/notario-0.0.16.tgz

